
FROM python:3.11-slim

RUN useradd -m appuser

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN chown -R appuser:appuser /app
USER appuser

EXPOSE 8080

CMD [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080" ]
